language: node_js
node_js:
- 6
- 8
- lts/*
- node
env:
  global:
    secure: xtw4euZOcbcv3X2Ok5u7JdCO367hPcflKEKR6Eky4CH+hcKqQi5kotB2UMN9iHnXPIEjmXzJ/3h8cY2/c89VpDYIHz7HcH8MfqYrP/9KiB2K9UoP0b6XLjR9q6RQ1esV1IT9GgLs20Gn6wwZ7vmnPTL5a3Z5bZKA15uf/uxWC+gKwcx9XM/4mmWZQxP9JnYY1s6yjsO0Oalh2KPoPkAV1/YQ32I9xhNITtXSrJ5ilVpK3WzFEjJ3kZk7BKDND4UvRhyf/D1DvgpXwh8qBivqv9y5PyKJN2xJfhQGKZlrH24oQbg8aoP2aMtjb2mbXB5XP2ZR9pFp6nT3alO49CKE0PUnSLqhW7zkgG/zyU3idQDEgOm3a3nLWO7bncR1ilNaiJ6WUK2yFyXrx4aB1NtxOjoZsavz6k5LjC0qSvVZq9oGClezKkWpBD9X7WYE33L8JzZS7S5f7r1EsNEU4/39wPGQxjK4H0k5Y01OE5HFFHFGgiFBr0/LnjcNbqFZasSldZH0ro82fAy1pBRcqoWgqPOXdh+U0yDOwDMvzDg4ty1BoRTqqDy12O7MSP67osj2UD0S9cfFNfKdR3wH5P0W4TwLl2govc9lMPdubUE7Vo8vhSehCXx4Ki54bvTCVJdcapHmhdoFUaL/iMhS9HYSoOIZ1PYGHoPiivWFxeGHq4g=
